package exercise3_ant;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PARTZ
 */
import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement; 
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
    }
public static Connection myConn = null;
public static PreparedStatement myPStmt = null;
public static ResultSet myRs = null;
public static DefaultTableModel tmodel = new DefaultTableModel();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSubmit = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "LocationCode", "DatePosted", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COUNT", "AVG", "MAX", "MIN", "SUM" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("CHOOOSE FROM  THE FOLLOWING AGGREGATE FUNCTIONS");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 726, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void Connection()
    {
        try
        {
         myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbentries","root","");
        }
        catch(SQLException ex)
        {
        JOptionPane.showMessageDialog(this, "SQL Error (Select): " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        tmodel = (DefaultTableModel) jTable1.getModel();
    tmodel.setRowCount(0);

   if("COUNT".equals(jComboBox1.getSelectedItem()))
   {
    try {
         // Prepare Statement
        myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbentries","root","");
	    var sql="SELECT LocationCode, DatePosted, COUNT(Amount) AS total_amount FROM tblentry GROUP BY LocationCode, DatePosted ";
          myPStmt = myConn.prepareStatement(sql);   
         // Execute SQL query
          myRs = myPStmt.executeQuery();  
         
   // Show records from ResultSet
    while(myRs.next())
           {
             Vector row = new Vector();
             row.add(myRs.getString(1));
             row.add(myRs.getString(2));
             row.add(myRs.getString(3));
             
             
              tmodel.addRow(row);
           }
       }catch(Exception e)
       {
JOptionPane.showMessageDialog(null, e,"Show Record", JOptionPane.ERROR_MESSAGE);
       }
   }
   else if("MAX".equals(jComboBox1.getSelectedItem()))
   {
       try {
         // Prepare Statement
        myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbentries","root","");
	    var sql="SELECT LocationCode, DatePosted, MAX(Amount) AS total_amount FROM tblentry GROUP BY LocationCode, DatePosted ";
          myPStmt = myConn.prepareStatement(sql);   
         // Execute SQL query
          myRs = myPStmt.executeQuery();  
         
   // Show records from ResultSet
    while(myRs.next())
           {
             Vector row = new Vector();
             row.add(myRs.getString(1));
             row.add(myRs.getString(2));
             row.add(myRs.getString(3));
             
             
              tmodel.addRow(row);
           }
       }catch(Exception e)
       {
JOptionPane.showMessageDialog(null, e,"Show Record", JOptionPane.ERROR_MESSAGE);
       }
   }
   else if("MIN".equals(jComboBox1.getSelectedItem()))
   {
       try {
         // Prepare Statement
        myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbentries","root","");
	    var sql="SELECT LocationCode, DatePosted, MIN(Amount) AS total_amount FROM tblentry GROUP BY LocationCode, DatePosted ";
          myPStmt = myConn.prepareStatement(sql);   
         // Execute SQL query
          myRs = myPStmt.executeQuery();  
         
   // Show records from ResultSet
    while(myRs.next())
           {
             Vector row = new Vector();
             row.add(myRs.getString(1));
             row.add(myRs.getString(2));
             row.add(myRs.getString(3));
             
             
              tmodel.addRow(row);
           }
       }catch(Exception e)
       {
JOptionPane.showMessageDialog(null, e,"Show Record", JOptionPane.ERROR_MESSAGE);
       }
   }
   else if("AVG".equals(jComboBox1.getSelectedItem()))
   {
       try {
         // Prepare Statement
        myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbentries","root","");
	    var sql="SELECT LocationCode, DatePosted, AVG(Amount) AS total_amount FROM tblentry GROUP BY LocationCode, DatePosted ";
          myPStmt = myConn.prepareStatement(sql);   
         // Execute SQL query
          myRs = myPStmt.executeQuery();  
         
   // Show records from ResultSet
    while(myRs.next())
           {
             Vector row = new Vector();
             row.add(myRs.getString(1));
             row.add(myRs.getString(2));
             row.add(myRs.getString(3));
             
             
              tmodel.addRow(row);
           }
       }catch(Exception e)
       {
JOptionPane.showMessageDialog(null, e,"Show Record", JOptionPane.ERROR_MESSAGE);
       }
   }
   else if("SUM".equals(jComboBox1.getSelectedItem()))
   {
       try {
         // Prepare Statement
        myConn = DriverManager.getConnection("jdbc:mysql://localhost:3306/dbentries","root","");
	    var sql="SELECT LocationCode, DatePosted, SUM(Amount) AS total_amount FROM tblentry GROUP BY LocationCode, DatePosted ";
          myPStmt = myConn.prepareStatement(sql);   
         // Execute SQL query
          myRs = myPStmt.executeQuery();  
         
   // Show records from ResultSet
    while(myRs.next())
           {
             Vector row = new Vector();
             row.add(myRs.getString(1));
             row.add(myRs.getString(2));
             row.add(myRs.getString(3));
             
             
              tmodel.addRow(row);
           }
       }catch(Exception e)
       {
JOptionPane.showMessageDialog(null, e,"Show Record", JOptionPane.ERROR_MESSAGE);
       }
   }
    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
